# Generated by Django 4.2.6 on 2023-10-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfiles', '0002_role_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(max_length=1000)),
                ('PostingDate', models.DateField()),
                ('Status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], max_length=20)),
                ('NumberOfOpenings', models.IntegerField(null=True)),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfiles.manager')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected')], max_length=20)),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfiles.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
