# Generated by Django 4.2.6 on 2023-10-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_job_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'JobPostings'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name_plural': 'JobApplications'},
        ),
        migrations.AddField(
            model_name='job',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfiles.departments'),
        ),
    ]
