# Generated by Django 4.2.6 on 2023-10-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0005_manager_password_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Department_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='Department_id',
            new_name='id',
        ),
    ]
