# Generated by Django 4.2.6 on 2023-10-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0006_rename_department_name_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='Department_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
