# Generated by Django 4.2.6 on 2023-11-04 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('UserProfiles', '0008_remove_manager_password_remove_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userManagerID', models.IntegerField()),
                ('jobTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateOfPosting', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('numberOfApplications', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=20)),
                ('requirement', models.TextField()),
                ('hourlyWage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workHours', models.PositiveSmallIntegerField()),
                ('academicStatus', models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior'), ('graduate', 'Graduate')], max_length=20, null=True)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobID', models.IntegerField()),
                ('applicationID', models.IntegerField()),
                ('applicantStatus', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('City', models.CharField(blank=True, max_length=1000, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['type'], 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='Name',
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='role',
            name='role_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('applicant', 'Applicant')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.ManyToManyField(to='UserProfiles.role'),
        ),
    ]
