# Generated by Django 4.2.6 on 2023-11-04 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0009_jobpost_notification_profile_remove_job_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobID', models.IntegerField()),
                ('userApplication', models.IntegerField()),
                ('applicationStatus', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20, null=True)),
                ('waitlistPosition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academicStatus', models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior'), ('graduate', 'Graduate')], max_length=20, null=True)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('availability', models.TextField()),
                ('desiredWorkHours', models.PositiveSmallIntegerField()),
                ('preferredDepartment', models.CharField(max_length=100)),
                ('workStudyEligibility', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
