# Generated by Django 4.2.6 on 2023-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0010_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['type'], 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='role',
            name='role_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
