# Generated by Django 4.2.6 on 2023-11-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0011_alter_role_options_alter_role_role_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Role',
        ),
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfiles.role'),
        ),
    ]
