# Generated by Django 4.2.6 on 2023-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0013_remove_jobapplication_jobid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='preferredDepartment',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='waitlistPosition',
        ),
    ]
