# Generated by Django 4.2.6 on 2023-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0015_rename_academicstatus_jobapplication_academicstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('Manager', 'Manager'), ('Admin', 'Admin')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
