# Generated by Django 4.2.6 on 2023-11-05 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0017_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
