# Generated by Django 4.2.6 on 2023-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0018_alter_jobpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
