# Generated by Django 4.2.6 on 2023-11-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0020_alter_jobpost_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfiles.profile'),
        ),
    ]
