# Generated by Django 4.2.6 on 2023-11-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0027_rename_user_jobapplication_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='student',
            new_name='Student',
        ),
    ]
