# Generated by Django 4.2.6 on 2023-11-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0028_rename_student_jobapplication_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='jobPost',
        ),
    ]
