# Generated by Django 4.2.6 on 2023-11-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0029_rename_job_jobapplication_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
