# Generated by Django 4.2.6 on 2023-11-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0030_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ApplicationStatus',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='applied', max_length=20, null=True),
        ),
    ]
